# Generated by Django 4.0.2 on 2022-02-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_image',
            new_name='image',
        ),
    ]
